### ISSUE TITLE
Gating option not working

### ISSUE THREAD

**Issue by sbagur** [open-ephys-plugins/pulse-pal-output#1]
Hi
We are using the pulsepal plugin in openephys. We can trigger it successfully but the trigger results in a stimulation whether or not the gate is high. We are gating on TTL 4 of the rythm FPGA and we see that the TTL is going on and off with the visualisation but it has no effect on triggering the stimulation. Do you have any suggestions about how we could remedy this problem?
Thanks for any help you can provide
Best regards
Sophie Bagur

**Comment by jsiegle** [comment]
There was a bug in the gating logic, which I just fixed in the [`fix-gating`](https://github.com/open-ephys-plugins/pulse-pal-output/tree/fix-gating) branch. You can either compile this plugin from source to take advantage of it now, or wait until the new version is released. @anjaldoshi can you take care of putting a new release out?

**Comment by anjaldoshi** [comment]
Yep, on it!

**Comment by anjaldoshi** [comment]
New release is up! v0.1.1 is available to download via Plugin Installer.

**Comment by sbagur** [comment]
Hi Josh and @anjaldoshi
Thanks so much for getting on this so quickly. We will test it on Monday and let you know.

**Comment by bmaheo** [comment]
Hey @anjaldoshi & @jsiegle ,

I was the one having gating trouble with PulsePal plugin on OpenEphys (thanks @sbagur )
I tried your new version, thanks a lot, it was really fast !

But it seems that I encounter some difficulties, while trying to build the plugin with cmake, I have this error :
"In file included from /home/mobs/plugin-GUI/Plugins/pulse-pal-output-fix-gating/OpenEphysLib.cpp:25:0:
/home/mobs/plugin-GUI/Plugins/pulse-pal-output-fix-gating/PulsePalOutput.h:95:10: error: ‘void PulsePalOutput::handleTTLEvent(TTLEventPtr)’ marked ‘override’, but does not override
     void handleTTLEvent (TTLEventPtr event) override"
     
I just begin on OpenEphys and I apologize in advance if this is a basic error on my account.
     
Best regards,

Baptiste MAHEO

**Comment by jsiegle** [comment]
Hi Baptiste,

Make sure your directory layout looks like this before running CMake:

```
Code
├── plugin-GUI
│   ├── Build
│   ├── Source
│   └── ...
├── OEPlugins
│   └── pulse-pal-output
│       ├── Build
│       ├── Source
│       └── ...
```

It looks like you put the Pulse Pal code inside the directory for the GUI's default plugins, which won't work for plugins that are meant to be compiled externally.

**Comment by bmaheo** [comment]
It's working ! 
Thanks a lot
